# 服务器配置
server:
  port: 8080

spring:
  application:
    name: schedule-job-admin
  # Redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      connect-timeout: 3000
      database: 0 # Redis数据库索引（0-15）
      username:
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          min-idle: 0
          enabled: true
  # quartz 调度器配置
  quartz:
    job-store-type: jdbc
    scheduler-name: jobSchedule
    auto-startup: true
    overwrite-existing-jobs: false
    startup-delay: 10s
    properties:
      org:
        quartz:
          dataSource:
            QuartzDS:
              driver: com.mysql.cj.jdbc.Driver
              dataSourceName: quartzDataSource
          jobStore:
            #程序启动后直接使用已建的表
            initializeSchema: never
            #如果不需要将调度命令（例如添加和删除triggers）绑定到其他事务，那么可以通过使用 JobStoreTX 管理事务
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            #设置数据库驱动代理，StdJDBCDelegate 是一个使用 JDBC 代码来执行其工作的代理. 其他代理可以在"org.quartz.impl.jdbcjobstore“包或其子包中找到
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            #通知 JobStore 使用的表前缀
            tablePrefix: QRTZ_
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool  #quartz 使用的线程池类型，org.quartz.spi.ThreadPool
            threadCount: 15   #线程池中的线程总个数，表示最多可以同时执行的个任务/作业个数
            threadPriority: 5   #线程优先级
            threadsInheritContextClassLoaderOfInitializingThread: true #线程继承初始化线程的上下文类加载器